name: Firebase Continuos Deployment

on: 
  push:
    branches: [master]
    
jobs:
  deploy_live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run clean
        run: npm run clean
      - name: Run build
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.FIREBASE_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BGECKO_A882B }}"
          projectId: bgecko-a882b
          channelId: live








  
   
