name: Firebase Continuos Deployment

on: 
  push:
    branches: [master]
    
jobs:
  install-dependencies:
    name: Install-dependencies
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Install dependencies
      run: npm ci
    - name: Run clean
      run: npm run clean
    - name: Run build
      run: npm run build
      
  deploy:
    name: deploy
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master 
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
